### ISSUE TITLE
Função LimpaEspacos

### ISSUE THREAD

**Issue by eduardoghi** [llutti/vscode-language-lsp#10]
Falta a função https://documentacao.senior.com.br/gestaoempresarialerp/5.10.3/regra_funcoes/limpaespacos.htm no [lsp-internal-templates.ts](https://github.com/llutti/vscode-language-lsp/blob/main/server/src/lsp-internal-templates.ts)

**Comment by llutti** [comment]
Boa Tarde, Eduardo!

Acabei de liberar uma nova versão com esta função adicionada.

Agradecido pela sugestão.
