### ISSUE TITLE
Pequenos bugs referentes ao intellisense

### ISSUE THREAD

**Issue by luicfrr** [llutti/vscode-language-lsp#12]
Olá, ao utilizar a extensão eu percebi dois pequenos bugs referentes ao intellisense:
- [x] É recomendado incluir um Bloco INICIO/FIM para o "SENAO". Utilizando o `senão` o intellisense recomenda o uso de `Inicio/Fim` ao utilizar chaves mesmo esta sendo uma sintaxe válida. Exemplo:
```
se(condição) {
  ....
} senao { // -> o "erro" aparece aqui
  ....
}
```
- [x] Intellisense não aponta erros caso um ponto e vírgula (;) esteja ausente ao final de strings. Exemplo:
```
aMsg = "Uma mensagem de teste" // intellisense NÃO reporta a falta de ponto e virgula
Mensagem(Retorna, aMsg) // intellisense reporta a falta de ponto e virgula
```

**Comment by llutti** [comment]
Boa Tarde!

Correções liberadas na versão 1.2.12 da extensão.
