### ISSUE TITLE
Compilar Linguagem

### ISSUE THREAD

**Issue by PedroEmmanuelBuerger** [llutti/vscode-language-lsp#13]
Opa, Gostaria de ver se a linguagem é alto compilável, ou se precisa de algum App terceiro para poder rode o código feito em LSP no vscode.
se for auto compilável, poderia me explicar quais configurações devem ser feitas?

Agradeço.

**Comment by llutti** [comment]
Olá, Pedro!

A LSP (_Linguagem Senior de Progamação_) é uma _linguagem de script_ utilizada unicamente dentro dos produtos desenvolvidos pela [Senior Sistemas](https://www.senior.com.br/) de Blumenau. Eu mesmo não tenho acesso ao compilador interno da Senior para a LSP. Esta extensão apenas auxilia na codificação das regras.

Luciano
