### ISSUE TITLE
Regras não sendo tratadas pela solução

### ISSUE THREAD

**Issue by MuriloFloriani** [llutti/vscode-language-lsp#2]
Abrindo um txt com a regra em questão, a extensão aparentemente não reconheceu o arquivo como LSP e não aplicou os devidos tratamento. Basicamente é como seu eu estivesse abrindo um arquivo qualquer.

Dentro da configs da extensão eu alterei o paramêtro para ERP, depois para Senior e não mudou a situação. 

Não sou um usuário avançado em VS-Code , talvez esteja deixando alguma configuração para trás, de qualquer forma precisaria desta analise.

Obrigado

**Comment by llutti** [comment]
Olá Murilo!
 Para ativar a extensão para os seus arquivos tem algumas opções:
1. Criar o arquivo com a extensão ".lspt";
2. Nas configurações do VSCode (global ou para o workspace) associar os arquivos ".txt" para utilizar a extensão LSP;
![image](https://user-images.githubusercontent.com/24873687/218815340-70e61292-0660-48b7-9935-1725a5657150.png)

3. Depois de abrir o arquivo, ir modificar a "linguagem do arquivo". Isso pode ser feito pela barra de status do VSCode.
![image](https://user-images.githubusercontent.com/24873687/218815281-e256c39d-706e-460b-ac07-46072608a4d1.png)

**Comment by MuriloFloriani** [comment]
Olá Luciano,

Show, consegui fazer os ajustes, muito obrigado pela ajuda e parabéns pela iniciativa!!!.

**Comment by llutti** [comment]
Olá Murilo!

Que bom que você conseguiu resolver seu problema.

Fico feliz em auxiliar.
