### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'range')

### ISSUE THREAD

**Issue by luicfrr** [llutti/vscode-language-lsp#8]
Olá, ao tentar utilizar a extensão no VsCode 1.81.1 ao tentar definir variáveis e apertando tab recebo o seguinte erro abaixo:

```
TypeError: Cannot read properties of null (reading 'range')
    at t.checkSintaxe (/Users/ncsistemas/.vscode/extensions/llutti.lsp-1.2.8/dist/server.js:1:338738)
    at S (/Users/ncsistemas/.vscode/extensions/llutti.lsp-1.2.8/dist/server.js:1:346325)
[Error - 17:19:26] The Linguaguem de Suporte para "Linguaguem Senior de Programação" server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by llutti** [comment]
Olá Luiz Carlos!
Estou tentando reproduzir o erro que você relatou, mas não estou conseguido. Você consegue me enviar um exemplo de regra e como reproduzir o erro, por favor.

**Comment by luicfrr** [comment]
@llutti segue abaixo um gif mostrando o erro e como acontece comigo:

![erro_lspt_vscode](https://github.com/llutti/vscode-language-lsp/assets/60632638/454d57ad-cb55-4def-82be-88920d9f5af0)

**Comment by llutti** [comment]
Olá @nonam4, Consegui resolver o problema. Agradecido pelo apoio.

**Comment by luicfrr** [comment]
@llutti já atualizei a extensão e agora ta funcionando legal, obrigado pela atenção e agilidade também 😁
